### ISSUE TITLE
Why 128 bytes?

### ISSUE THREAD

**Issue by Avi-D-coder** [smol-rs/cache-padded#1]
What CPUs have a 128 byte cache line?
Are there any common ones?
Perhaps a compile flag would be a good idea?

**Comment by kubo39** [comment]
@Avi-D-coder You can see why here.

https://github.com/crossbeam-rs/crossbeam/pull/331
https://github.com/crossbeam-rs/crossbeam/pull/499

**Comment by Mart-Bogdan** [comment]
Seems like issue only for Intel, not AMD. as mentioned in crossbeam PR discussion
