### ISSUE TITLE
Deprecate in favor of crossbeam_utils::CachePadded

### ISSUE THREAD

**Issue by notgull** [smol-rs/cache-padded#10]
The `CachePadded` structure in this crate is identical to the one in the `crossbeam_utils` crate. Is there any particular reason why the original author split it out into its own crate? If not, I'd say that we should use the latter instead and reduce the need to sync changes between this one and the one from `crossbeam`.

**Comment by taiki-e** [comment]
> Is there any particular reason why the original author split it out into its own crate?

I thought this was for users who stick to `#![forbid(unsafe_code)]`, but I'm not sure exactly why.
One user mentioned the number of dependencies (https://github.com/smol-rs/cache-padded/issues/7). That said, disabling the default features of the `crossbeam_utils` should virtually remove that problem (cfg_if only).
