### ISSUE TITLE
Get latest updates from crossbeam-utils?

### ISSUE THREAD

**Issue by mgeier** [smol-rs/cache-padded#7]
I've just seen https://github.com/crossbeam-rs/crossbeam/pull/636, which updated a few cache line sizes.

Over there, @taiki-e said:

> when this merged, I'll send a same patch to smol-rs/cache-padded

Should these changes also be included here?

I'd prefer using this `CachePadded` because it has fewer dependencies than the one from `crossbeam-utils`.

**Comment by taiki-e** [comment]
Done in 1.2.0.

**Comment by mgeier** [comment]
Thanks @taiki-e!

It's not a big deal, but the README still contains the old information.

**Comment by taiki-e** [comment]
> It's not a big deal, but the README still contains the old information.

Good catch. I've updated docs (https://github.com/smol-rs/cache-padded/commit/c892839b103fbce7a2d8ae2329488491f7d717cf).
