### ISSUE TITLE
test failures on armv7 since version 1.2.0

### ISSUE THREAD

**Issue by decathorpe** [smol-rs/cache-padded#9]
Looks like some of the changes that were merged since the last release break tests on ARM:

- "distance" unit test fails:

```
---- distance stdout ----
thread 'distance' panicked at 'assertion failed: unsafe { a.offset(64) } <= b', tests/padding.rs:30:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

- one doctest fails:

```
---- src/lib.rs - (line 29) stdout ----
Test executable failed (exit code 101).
stderr:
thread 'main' panicked at 'assertion failed: addr2 - addr1 >= 64', src/lib.rs:10:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

EDIT: For completeness, I should add the following details:

- rustc 1.57.0 on Fedora Linux
- architecture: armv7-unknown-linux-gnueabihf

**Comment by taiki-e** [comment]
Thanks. This is the same issue as https://github.com/crossbeam-rs/crossbeam/issues/668 and https://github.com/crossbeam-rs/crossbeam/pull/641, and we need to update tests.

**Comment by decathorpe** [comment]
Oh no, I reported that bug too ... now I understand why the error message sounded familiar :D

I'll ignore that test failure for now, thanks for investigating.

**Comment by taiki-e** [comment]
Closing as we no longer maintain this crate (see https://github.com/smol-rs/cache-padded/issues/10 for more).
